export default[
  {
    "modelYear": 2021,
    "make": "Buick",
    "model": "Enclave",
    "makeCD": 4,
    "DD_MAKE_CD": "B",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "ENCL"
  },
  {
    "modelYear": 2021,
    "make": "Buick",
    "model": "Encore",
    "makeCD": 4,
    "DD_MAKE_CD": "B",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "ENCO"
  },
  {
    "modelYear": 2021,
    "make": "Buick",
    "model": "EncoreGX",
    "makeCD": 4,
    "DD_MAKE_CD": "B",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "ENGX"
  },
  {
    "modelYear": 2021,
    "make": "Buick",
    "model": "Envision",
    "makeCD": 4,
    "DD_MAKE_CD": "B",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "ENVS"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "Escalade",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "ESCA"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "Escalade_ESV",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "ESCV"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "XT4",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "XT41"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "XT5",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "XT51"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "XT6",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "XT61"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "CT4",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "CT41"
  },
  {
    "modelYear": 2021,
    "make": "Cadillac",
    "model": "CT5",
    "makeCD": 6,
    "DD_MAKE_CD": "K",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "Luxary",
    "modelSubTypeFR": "luxe",
    "modelCD": "CT51"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "BOLT_EV",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "Electric",
    "modelSubTypeFR": "Électrique",
    "modelCD": "BOLT"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Camaro",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "Performance, Convertible",
    "modelSubTypeFR": "Performance, Convertible",
    "modelCD": "CAMA"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Colorado",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "COLO"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Corvette",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "Performance",
    "modelSubTypeFR": "Performance, Convertible",
    "modelCD": "CORV"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Equinox",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "EQUI"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Malibu",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "MALI"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Silverado",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SILV"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Silverado High Country",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SILH"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Spark",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "CAR",
    "modelTypeFR": "VOITURES",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "SPAR"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Suburban",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "SUBU"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Tahoe",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TAHO"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Trailblazer",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TRBL"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Traverse",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TRAV"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Trax",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TRAX"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Blazer",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "BLAZ"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Acadia",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "ACAD"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Canyon",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "CANY"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Sierra",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SIER"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Sierra3500HD",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SIEH"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Terrain",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TERR"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Yukon",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "YUKO"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Yukon Denali",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "YUKD"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "YukonXL",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "YUKX"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Yukon XL Denali",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "YUXD"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Silverado HD",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SILH"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Trailblazer RS",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TBRS"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Silverado Trail Boss",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SLTB"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Equinox Premier",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "EQPR"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Silverado Custom",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "SLCM"
  },
  {
    "modelYear": 2021,
    "make": "Chevrolet",
    "model": "Trailblazer Activ",
    "makeCD": 1,
    "DD_MAKE_CD": "C",
    "modelTypeEN": "SUV",
    "modelTypeFR": "VUS",
    "modelSubTypeEN": "",
    "modelSubTypeFR": "",
    "modelCD": "TBAV"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Sierra Denali",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SIDL"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Sierra SLT",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SIST"
  },
  {
    "modelYear": 2021,
    "make": "GMC",
    "model": "Sierra SLE",
    "makeCD": 10,
    "DD_MAKE_CD": "G",
    "modelTypeEN": "TRUCK",
    "modelTypeFR": "CAMIONS",
    "modelSubTypeEN": "Pickup",
    "modelSubTypeFR": "Pickup",
    "modelCD": "SISE"
  }
]