export default[
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Buick",
    "MODEL": "Enclave",
    "MAKE_CD": 4,
    "DD_MAKE_CD": "B",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "ENCL"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Buick",
    "MODEL": "Encore",
    "MAKE_CD": 4,
    "DD_MAKE_CD": "B",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "ENCO"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Buick",
    "MODEL": "EncoreGX",
    "MAKE_CD": 4,
    "DD_MAKE_CD": "B",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "ENGX"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Buick",
    "MODEL": "Envision",
    "MAKE_CD": 4,
    "DD_MAKE_CD": "B",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "ENVS"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "Escalade",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "ESCA"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "Escalade_ESV",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "ESCV"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "XT4",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "XT41"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "XT5",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "XT51"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "XT6",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "XT61"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "CT4",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "CT41"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Cadillac",
    "MODEL": "CT5",
    "MAKE_CD": 6,
    "DD_MAKE_CD": "K",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "Luxary",
    "MODEL_SUBTYPE_FR": "luxe",
    "MODEL_CD": "CT51"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "BOLT_EV",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "Electric",
    "MODEL_SUBTYPE_FR": "Électrique",
    "MODEL_CD": "BOLT"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Camaro",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "Performance, Convertible",
    "MODEL_SUBTYPE_FR": "Performance, Convertible",
    "MODEL_CD": "CAMA"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Colorado",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "COLO"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Corvette",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "Performance",
    "MODEL_SUBTYPE_FR": "Performance, Convertible",
    "MODEL_CD": "CORV"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Equinox",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "EQUI"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Malibu",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "MALI"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Silverado",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SILV"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Silverado High Country",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SILH"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Spark",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "CAR",
    "MODEL_TYPE_FR": "VOITURES",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "SPAR"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Suburban",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "SUBU"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Tahoe",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TAHO"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Trailblazer",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TRBL"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Traverse",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TRAV"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Trax",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TRAX"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Blazer",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "BLAZ"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Acadia",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "ACAD"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Canyon",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "CANY"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Sierra",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SIER"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Sierra3500HD",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SIEH"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Terrain",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TERR"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Yukon",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "YUKO"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Yukon Denali",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "YUKD"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "YukonXL",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "YUKX"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Yukon XL Denali",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "YUXD"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Silverado HD",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SILH"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Trailblazer RS",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TBRS"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Silverado Trail Boss",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SLTB"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Equinox Premier",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "EQPR"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Silverado Custom",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "SLCM"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "Chevrolet",
    "MODEL": "Trailblazer Activ",
    "MAKE_CD": 1,
    "DD_MAKE_CD": "C",
    "MODEL_TYPE_EN": "SUV",
    "MODEL_TYPE_FR": "VUS",
    "MODEL_SUBTYPE_EN": "",
    "MODEL_SUBTYPE_FR": "",
    "MODEL_CD": "TBAV"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Sierra Denali",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SIDL"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Sierra SLT",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SIST"
  },
  {
    "MODEL_YEAR": 2021,
    "MAKE": "GMC",
    "MODEL": "Sierra SLE",
    "MAKE_CD": 10,
    "DD_MAKE_CD": "G",
    "MODEL_TYPE_EN": "TRUCK",
    "MODEL_TYPE_FR": "CAMIONS",
    "MODEL_SUBTYPE_EN": "Pickup",
    "MODEL_SUBTYPE_FR": "Pickup",
    "MODEL_CD": "SISE"
  }
]